/*** Table: file_bucket ***/

CREATE TABLE file_bucket (
    id integer NOT NULL,
    tstamp timestamp without time zone,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES resource (id)
);

COMMENT ON TABLE file_bucket IS 'file_bucket';

/*** Table: file_bucket_file ***/

CREATE TABLE file_bucket_file (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_bucket_id integer NOT NULL,
    fileobj_id integer NOT NULL,
    name character varying(255) NOT NULL,
    mime_type character varying NOT NULL,
    size bigint NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (file_bucket_id, name),
    FOREIGN KEY (file_bucket_id) REFERENCES file_bucket (id),
    FOREIGN KEY (fileobj_id) REFERENCES fileobj (id)
);

COMMENT ON TABLE file_bucket_file IS 'file_bucket';
